name: Tests

on:
  pull_request:
    paths:
      - ".cargo/*.toml"
      - ".github/workflows/*.yaml"
      - "Cargo.*"
      - "mutants_attrs/**"
      - "**/src/**"
      - "**/tests/**"
  push:
    branches:
      - main

# see https://matklad.github.io/2021/09/04/fast-rust-builds.html
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  CARGO_MUTANTS_MINIMUM_TEST_TIMEOUT: 60

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ci-${{ github.repository }}-${{ github.ref }}
      cancel-in-progress: true

    # Setup Rust
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - name: Install just
        run: cargo install just
      - name: Rustfmt
        run: just fmt
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components:  clippy
      - name: Show Cargo and rustc version
        run: |
          cargo --version
          rustc --version
      - name: Install cargo-mutants
        run: |
          cargo install cargo-mutants
          cargo install cargo-deny
          cargo install cargo-semver-checks
      - name: Run tests
        run: just test
